print("This files is created in RStudio")

1+1
num[1:4, 1:2] 1 2 3 4 5 6 7 8
matrix(c(1,2,3,4,5,6,7,8),nrwo = 4 , ncol = 2 )
matrix(c(1,2,3,4,5,6,7,8),nrow = 4 , ncol = 2 )
matrix(c(1,2,3,4,5,6,7,8),nrow = 4 , ncol = 2 )
matrix(c(1,2,3,4,5,6,7,8),nrow = 4 , ncol = 2 )
matrix(c(1,2,3,4,5,6,7,8),nrow = 4 , ncol = 2 )
source('D:/DataSciene/RProject/QuickRCommands.R')
example <- matrix(c(1,2,3,4,5,6,7,8),nrow = 4 , ncol = 2 )
View(example)
example <- matrix(c(1,2,3,4,5,6,7,8),nrow = 4 , ncol = 2 )
view(example)
View(example)
install.packages("ggplot2")
install.packages(c("boot", "class", "foreign", "KernSmooth", "MASS", "nnet", "rlang", "spatial"))
View(example)
writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")
sys.which(make)
Sys.which(make)
Sys.getenv("PATH")
Sys.which(make)
writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")
Sys.which(make)
install.packages("jsonlite", type = "source")
isntall.packages("devtools")
install.packages("devtools")
library(devtools)
install_github(hilaryparker/names)
install_github("hilaryparker/names")
installed.packages()
library(jsonlite)
library(ggplot2)
session_info()
version
sessionInfo()
help(package = "ggplot2")
help(package = "devtools")
install.packages("KernSmooth")
Ssession_info(pkgs="KernSmooth")
sessionInfo("KernSmooth")
library(KernSmooth)
packageDescription('KernSmooth')
sessionifo()
sessionInfo()
savehistory("D:/DataSciene/RProject/QuickRCommands.R")
print("This Quick Commands will live on the Web Git Now")
